# Generated by Django 6.0.4 on 2026-04-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('carga_horaria', models.IntegerField()),
                ('validade', models.IntegerField(help_text='Validade em dias')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_validade', models.DateField()),
                ('status', models.CharField(choices=[('ATIVO', 'Conectado à Força'), ('VENCIDO', 'Desconectado da Força')], max_length=10)),
                ('relatorio', models.TextField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='missoes/')),
                ('jedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.jedi')),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamentos.treinamento')),
            ],
        ),
    ]
