# Generated by Django 6.0.4 on 2026-04-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_jedi', models.CharField(max_length=50, unique=True)),
                ('templo', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('PADAWAN', 'Padawan'), ('CAVALEIRO', 'Cavaleiro Jedi'), ('MESTRE', 'Mestre Jedi')], max_length=20)),
                ('foto', models.ImageField(upload_to='jedi_fotos/')),
                ('emblema', models.ImageField(upload_to='emblemas/')),
            ],
        ),
    ]
